// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PasswordToggleController from "./password_toggle_controller"
application.register("password-toggle", PasswordToggleController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import EditorController from "./editor_controller"
application.register("editor", EditorController)

import ChapterPanelController from "./chapter_panel_controller"
application.register("chapter-panel", ChapterPanelController)

import AutoSaveController from "./auto_save_controller"
application.register("auto-save", AutoSaveController)

import WordCountController from "./word_count_controller"
application.register("word-count", WordCountController)
